name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: aayush-12321
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
          filename: github-metrics.svg
